### ISSUE TITLE
Cannot delete root files in uefn internal

### ISSUE THREAD

**Issue by Xowerr** [gamerbross/UEFN-Unlocker#4]
When I try to delete a plugin of FortniteGame it cannot be deleted, This also happens on some folders located in FortniteGame/Content and other files found in the Fortnite files.
I was wondering if you can delete or disable fortnite root files in the internal version of uefn.
![error](https://github.com/gamerbross/UEFN-Unlocker/assets/148602409/01fd4657-da8d-41e0-83d5-6809b9707f43) 
### Permissions are from the "No-valkyrie-plugin-pak" without extra modifications to the uefn exe. [https://github.com/gamerbross/no-valkyrie-plugin-pak]("no-valkyrie-plugin-pak")

**Comment by gamerbross** [comment]
bro that will screw up everything, why would you wanna do that

**Comment by Xowerr** [comment]
> bro that will screw up everything, why would you wanna do that

Because I need to start in-game because the editor sometimes crashes in different version
